#!/bin/zsh

ListGen=(net net/filter)

./ini -n
# get option
while getopts "ao" opt; do
  case $opt {
  a ) OptAct=true ;;
  o ) OptOut=true ;;
  }
done
# generate files
cp -Rf src/out/* out
cp -f LICENSE out/LICENSE
for item in ${ListGen[@]}; {
  python3 src/${item}/main.py
}
if [[ -z $OptAct ]] {
  # release
  if [[ -n $OptOut ]] {
    cd out
    git add -qA
    git commit -qm gen --amend --reset-author
    git push -qf
  }
}
