#!/bin/zsh

while getopts "anr:" opt; do
  case $opt {
  a ) OptAct=true ;;
  n ) OptNot=true ;;
  r ) OptRmt=true
      ArgRmt=$optarg ;;
  }
done
if [[ -z $OptNot ]] {
  # install dependencies
  sudo apt install -y zsh git python3
  python3 -m pip install pyyaml requests
}
if [[ -z $OptAct ]] {
  if [[ -z $OptNot ]] {
    # update remote
    if [[ -n $OptRmt ]] {
      git submodule set-url out $ArgRmt
    }
    # install submodule
    git submodule update --init --recursive
  }
  # check branch
  cd out
  git checkout -qf etc
  git pull -q --rebase
}
