#!/bin/sh
while getopts "ai" opt; do case $opt in
  a)
    poetry install --only main;;
  i)
    if ! [ -x "$(command -v poetry)" ]; then
      pip install poetry; fi;
    poetry update --sync;;
esac; done;
poetry run python src/run.py "$@";